import type { Book } from './reading';

// The shelf, in render order: shelf groups follow SHELVES, books follow this array.
// One entry is one book — a series is several spines, not one. To add a book,
// append one entry here; nothing else in the repo needs editing. Pick a `spine`
// that differs from the entry above it on the same shelf (see spec Invariant 3).
export const READING_LIST: readonly Book[] = [
  {
    id: 'mythical-man-month',
    title: 'The Mythical Man-Month',
    author: 'Frederick P. Brooks Jr.',
    shelf: 'technical',
    spine: 'ink',
  },
  {
    id: 'machine-learning-in-production',
    title: 'Machine Learning in Production: From Models to Products',
    author: 'Christian Kästner',
    shelf: 'technical',
    spine: 'teal',
  },
  {
    id: 'operating-systems-three-easy-pieces',
    title: 'Operating Systems: Three Easy Pieces',
    author: 'Remzi H. Arpaci-Dusseau and Andrea C. Arpaci-Dusseau',
    shelf: 'technical',
    spine: 'sand',
  },
  {
    id: 'harry-potter-sorcerers-stone',
    title: 'Harry Potter and the Sorcerer’s Stone',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'clay',
  },
  {
    id: 'harry-potter-chamber-of-secrets',
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'teal',
  },
  {
    id: 'harry-potter-prisoner-of-azkaban',
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'ink',
  },
  {
    id: 'harry-potter-goblet-of-fire',
    title: 'Harry Potter and the Goblet of Fire',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'sand',
  },
  {
    id: 'harry-potter-order-of-the-phoenix',
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'teal',
  },
  {
    id: 'harry-potter-half-blood-prince',
    title: 'Harry Potter and the Half-Blood Prince',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'clay',
  },
  {
    id: 'harry-potter-deathly-hallows',
    title: 'Harry Potter and the Deathly Hallows',
    author: 'J. K. Rowling',
    shelf: 'fiction',
    spine: 'sand',
  },
  {
    id: 'a-game-of-thrones',
    title: 'A Game of Thrones',
    author: 'George R. R. Martin',
    shelf: 'fiction',
    spine: 'ink',
  },
  {
    id: 'a-clash-of-kings',
    title: 'A Clash of Kings',
    author: 'George R. R. Martin',
    shelf: 'fiction',
    spine: 'clay',
  },
  {
    id: 'fire-and-blood',
    title: 'Fire & Blood',
    author: 'George R. R. Martin',
    shelf: 'fiction',
    spine: 'sand',
  },
  {
    id: 'the-lightning-thief',
    title: 'The Lightning Thief',
    author: 'Rick Riordan',
    shelf: 'fiction',
    spine: 'teal',
  },
  {
    id: 'the-sea-of-monsters',
    title: 'The Sea of Monsters',
    author: 'Rick Riordan',
    shelf: 'fiction',
    spine: 'ink',
  },
  {
    id: 'the-titans-curse',
    title: 'The Titan’s Curse',
    author: 'Rick Riordan',
    shelf: 'fiction',
    spine: 'sand',
  },
  {
    id: 'the-battle-of-the-labyrinth',
    title: 'The Battle of the Labyrinth',
    author: 'Rick Riordan',
    shelf: 'fiction',
    spine: 'clay',
  },
  {
    id: 'the-last-olympian',
    title: 'The Last Olympian',
    author: 'Rick Riordan',
    shelf: 'fiction',
    spine: 'teal',
  },
];
